module.exports={
    configureWebpack:{
        resolve:{
            alias:{
                'assets':'@/assets',
                'common':'@/common',
                'components':'@/components',
                'anetwork':'@/network',
                'views':'@/views',
            }
        }
    }
}